"""Phase and implementation status constants."""

PHASE = "phase2b-lossless-investigation-memory-storage"
RUNTIME_IMPLEMENTATION_STATUS = "storage-substrate-only"
INVESTIGATION_MEMORY_STATUS = "storage-only-partial"
INVESTIGATION_MEMORY_STORAGE_STATUS = "lossless-local-storage-only"
INVESTIGATION_MEMORY_RETRIEVAL_STATUS = "not-implemented"
CONTEXT_MEMORY_VALIDATOR_STATUS = "semantic-validators-only"
MODEL_CONTEXT_INTEGRATION_STATUS = "not-implemented"
ALERTFORGE_STATUS = "not-implemented"
BENCHMARK_STATUS = "not-implemented"
CUSTOMER_READINESS_STATUS = "blocked"
